# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\domanic\qt\add_area_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_area(object):
    def setupUi(self, add_area):
        add_area.setObjectName("add_area")
        add_area.resize(400, 142)
        self.lineEdit = QtWidgets.QLineEdit(add_area)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(add_area)
        self.label.setGeometry(QtCore.QRect(26, 40, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(add_area)
        self.buttonBox.setGeometry(QtCore.QRect(220, 100, 159, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(add_area)
        self.label_3.setGeometry(QtCore.QRect(26, 15, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_region = QtWidgets.QLabel(add_area)
        self.label_region.setGeometry(QtCore.QRect(105, 15, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_region.setFont(font)
        self.label_region.setObjectName("label_region")
        self.id_region = QtWidgets.QLabel(add_area)
        self.id_region.setGeometry(QtCore.QRect(30, 110, 47, 13))
        self.id_region.setObjectName("id_region")

        self.retranslateUi(add_area)
        QtCore.QMetaObject.connectSlotsByName(add_area)

    def retranslateUi(self, add_area):
        _translate = QtCore.QCoreApplication.translate
        add_area.setWindowTitle(_translate("add_area", "Добавить площадь"))
        self.label.setText(_translate("add_area", "Введите название площади:"))
        self.label_3.setText(_translate("add_area", "Регион:"))
        self.label_region.setText(_translate("add_area", "название региона"))
        self.id_region.setText(_translate("add_area", "id region"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_area = QtWidgets.QWidget()
    ui = Ui_add_area()
    ui.setupUi(add_area)
    add_area.show()
    sys.exit(app.exec_())
