# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\domanic\qt\add_region_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_region(object):
    def setupUi(self, add_region):
        add_region.setObjectName("add_region")
        add_region.resize(400, 104)
        self.lineEdit = QtWidgets.QLineEdit(add_region)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(add_region)
        self.label.setGeometry(QtCore.QRect(26, 10, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(add_region)
        self.buttonBox.setGeometry(QtCore.QRect(220, 70, 159, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(add_region)
        QtCore.QMetaObject.connectSlotsByName(add_region)

    def retranslateUi(self, add_region):
        _translate = QtCore.QCoreApplication.translate
        add_region.setWindowTitle(_translate("add_region", "Добавить регион"))
        self.label.setText(_translate("add_region", "Введите название региона:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_region = QtWidgets.QWidget()
    ui = Ui_add_region()
    ui.setupUi(add_region)
    add_region.show()
    sys.exit(app.exec_())
