# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\domanic\qt\add_well_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_well(object):
    def setupUi(self, add_well):
        add_well.setObjectName("add_well")
        add_well.resize(400, 164)
        self.lineEdit = QtWidgets.QLineEdit(add_well)
        self.lineEdit.setGeometry(QtCore.QRect(20, 83, 361, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(add_well)
        self.label.setGeometry(QtCore.QRect(26, 63, 351, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(add_well)
        self.buttonBox.setGeometry(QtCore.QRect(220, 123, 159, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_3 = QtWidgets.QLabel(add_well)
        self.label_3.setGeometry(QtCore.QRect(26, 15, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_region = QtWidgets.QLabel(add_well)
        self.label_region.setGeometry(QtCore.QRect(105, 15, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_region.setFont(font)
        self.label_region.setObjectName("label_region")
        self.label_4 = QtWidgets.QLabel(add_well)
        self.label_4.setGeometry(QtCore.QRect(26, 40, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_area = QtWidgets.QLabel(add_well)
        self.label_area.setGeometry(QtCore.QRect(105, 40, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_area.setFont(font)
        self.label_area.setObjectName("label_area")
        self.id_area = QtWidgets.QLabel(add_well)
        self.id_area.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.id_area.setObjectName("id_area")

        self.retranslateUi(add_well)
        QtCore.QMetaObject.connectSlotsByName(add_well)

    def retranslateUi(self, add_well):
        _translate = QtCore.QCoreApplication.translate
        add_well.setWindowTitle(_translate("add_well", "Добавить скважину"))
        self.label.setText(_translate("add_well", "Введите номер скважины:"))
        self.label_3.setText(_translate("add_well", "Регион:"))
        self.label_region.setText(_translate("add_well", "название региона"))
        self.label_4.setText(_translate("add_well", "Площадь:"))
        self.label_area.setText(_translate("add_well", "название площади"))
        self.id_area.setText(_translate("add_well", "id_area"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_well = QtWidgets.QWidget()
    ui = Ui_add_well()
    ui.setupUi(add_well)
    add_well.show()
    sys.exit(app.exec_())
