# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\domanic\qt\edit_user_interval.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_user_int(object):
    def setupUi(self, edit_user_int):
        edit_user_int.setObjectName("edit_user_int")
        edit_user_int.resize(266, 111)
        self.gridLayout_2 = QtWidgets.QGridLayout(edit_user_int)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.doubleSpinBox_start = QtWidgets.QDoubleSpinBox(edit_user_int)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_start.setFont(font)
        self.doubleSpinBox_start.setDecimals(2)
        self.doubleSpinBox_start.setMaximum(25000.0)
        self.doubleSpinBox_start.setObjectName("doubleSpinBox_start")
        self.gridLayout_24.addWidget(self.doubleSpinBox_start, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(edit_user_int)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_24.addWidget(self.label_11, 0, 1, 1, 1)
        self.doubleSpinBox_stop = QtWidgets.QDoubleSpinBox(edit_user_int)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.doubleSpinBox_stop.setFont(font)
        self.doubleSpinBox_stop.setDecimals(2)
        self.doubleSpinBox_stop.setMaximum(25000.0)
        self.doubleSpinBox_stop.setProperty("value", 0.0)
        self.doubleSpinBox_stop.setObjectName("doubleSpinBox_stop")
        self.gridLayout_24.addWidget(self.doubleSpinBox_stop, 0, 2, 1, 1)
        self.gridLayout_24.setColumnStretch(0, 3)
        self.gridLayout_24.setColumnStretch(2, 3)
        self.gridLayout.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.pushButton_color = QtWidgets.QPushButton(edit_user_int)
        self.pushButton_color.setObjectName("pushButton_color")
        self.gridLayout.addWidget(self.pushButton_color, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.lineEdit_title = QtWidgets.QLineEdit(edit_user_int)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.gridLayout_2.addWidget(self.lineEdit_title, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(edit_user_int)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(edit_user_int)
        QtCore.QMetaObject.connectSlotsByName(edit_user_int)

    def retranslateUi(self, edit_user_int):
        _translate = QtCore.QCoreApplication.translate
        edit_user_int.setWindowTitle(_translate("edit_user_int", "Изменить интервал"))
        self.label_11.setText(_translate("edit_user_int", "-"))
        self.pushButton_color.setText(_translate("edit_user_int", "color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_user_int = QtWidgets.QWidget()
    ui = Ui_edit_user_int()
    ui.setupUi(edit_user_int)
    edit_user_int.show()
    sys.exit(app.exec_())
